### ISSUE TITLE
Ports where data is insufficient

### ISSUE THREAD

**Issue by Rasbats** [Scratchydisk/ESP8266-Admiralty-Tiday-API#1]
Notice, for example, Lostwithiel and Truro do not have enough data to predict LW times/heights. Does your code trap for this and modify the table produced?

**Comment by Scratchydisk** [comment]
This software is purely a wrapper around the Tidal API, so it'll return whatever the Admiralty API returns to it.

**Comment by dt0001** [comment]
Hope you can help. Am I correct in that  Serial.begin missing from your example? Also I get the error Unable to create https connection to API host. Any Ideas? Many thanks.
