### ISSUE TITLE
Unable to create https connection to API host

### ISSUE THREAD

**Issue by dt0001** [Scratchydisk/ESP8266-Admiralty-Tiday-API#2]
Hope you can help. Am I correct in that Serial.begin is missing and #include "Configuration.h" should not be included in your example? Also I get the error Unable to create https connection to API host. Any Ideas? Many thanks.

**Comment by Scratchydisk** [comment]
You may well be right on the missing code, but it runs on my environment!

Regarding the https connection, there was a bug in libaxtls.a that prevented this working.  See the note on the readme of this project.  (Basically update the ESP8266 Arduino library or pull an updated libaxtls.a from an updated copy.)
