### ISSUE TITLE
Azure Wildcard Certificate Expiration

### ISSUE THREAD

**Issue by DeJHDante** [Scratchydisk/ESP8266-Admiralty-Tiday-API#3]
Hi Stewart

Many thanks for all your hard work on the project.
I have a working system but without the Azure certificate which expired in Jan 2020.
Can you tell me how to get a new thumbprint?
I have googled but not found anything very helpful.
I'm not overly worried about security in this project, but interested in the process.
Hope you don't mind after all this time!

David

/***** Thumbprint of the API's certificate ****
* If you're using this then you'll need to update it
* when the certificate is renewed.
*
* If you're really worried about security then you
* should manually check the API URL and certificate
* thumbprint against the API website to make sure
* this file hasn't been changed be some third party!
****/

// API uses an Azure wildcard certificate
// Subject: *.azure-api.net
// Expires: 11 Jan 2020
#define SSL_THUMBRPRINT_API "cb33e927a76acb77c8215aaf4f98a3ff78139069"

**Comment by Scratchydisk** [comment]
Hi,

You can get the thumbprint by opening the certificate from your web browser and copying the SHA1 fingerprint (and remove the spaces).

0A456D395CBEA74FE1A6789CEB35AE0C796B27BF is valid until 24th Feb 2022.  I've not tested it, but it should work.

**Comment by Scratchydisk** [comment]
Hi,

You can get the thumbprint by opening the certificate from your web browser and copying the SHA1 fingerprint (and remove the spaces).

0A456D395CBEA74FE1A6789CEB35AE0C796B27BF is valid until 24th Feb 2022.  I've not tested it, but it should work.

**Comment by DeJHDante** [comment]
Thank you, Scratchydisk!
